[project]
name = "semantic-aifr"
version = "0.1.0"
description = "Prototype package to create AI Flaw Reports in semantic web-ready formats, such as JSON-LD and RDF-Turtle."
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["rdflib>=7.1.3"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.optional-dependencies]
test = ["pytest>=7.0.0"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
